[package]
name = "cfs_rust_amalgamated"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c2rust-bitfields = "0.18.0"
f128 = "0.2.9"
libc = "0.2.153"
memoffset = "0.9.1"
